language: python

sudo: false

python:
  - 2.7
  - 3.6
  - 3.5
  - 3.4
  - pypy3
  - pypy

# whitelist
# gh-pages is otherwise ignored by Travis CI
# Use a regex to whitelist gh-pages and all branches
branches:
  only:
    - gh-pages
    - /.*/

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run  --append --source scripts test/test_gpo_member_photos.py
  - coverage run  --append --source scripts scripts/missing.py

after_success:
  - coverage report
  - coveralls
  - pip install pycodestyle
  - pycodestyle scripts/*.py
  - pyflakes scripts/*.py

matrix:
  fast_finish: true
